import React, { createContext, useContext, useState } from 'react'

type Lang = 'en' | 'de'

const translations = {
  en: {
    // Nav
    dashboard: 'Dashboard',
    qrCodes: 'QR Codes',
    feedback: 'Feedback',
    superAdmin: 'Super Admin',
    logout: 'Logout',
    // Auth
    signIn: 'Sign In',
    signingIn: 'Signing in...',
    signInSubtitle: 'Sign in to your account',
    noAccount: 'No account?',
    registerCompany: 'Register your company',
    alreadyHaveAccount: 'Already have an account?',
    createAccount: 'Create Account',
    creatingAccount: 'Creating account...',
    companyName: 'Company Name',
    email: 'Email',
    password: 'Password',
    // Dashboard
    overallPerformance: 'Overall performance',
    totalFeedback: 'Total Feedback',
    averageRating: 'Average Rating',
    outOf10: 'out of 10',
    active: 'Active',
    inactive: 'Inactive',
    activeQRCodes: 'Active QR Codes',
    filter: 'Filter:',
    allQRCodes: 'All QR Codes',
    showing: 'Showing:',
    topFeedback: '🏆 Top Feedback',
    needsAttention: '⚠️ Needs Attention',
    noComment: 'No comment',
    byQRCode: 'By QR Code',
    responses: 'responses',
    avg: 'avg',
    noFeedbackYet: 'No feedback yet.',
    shareQRCodes: 'Share your QR codes to start collecting feedback.',
    dailyChart: 'Daily — Last 30 Days',
    weeklyChart: 'Weekly — Last 4 Weeks',
    noDataPeriod: 'No feedback in this period yet.',
    ratingDistribution: 'Rating Distribution',
    // QR Codes page
    generateNew: 'Generate New QR Code',
    labelPlaceholder: 'e.g. Main Entrance, Table 5...',
    create: 'Create',
    creating: 'Creating...',
    noQRCodes: 'No QR codes yet.',
    createOneToStart: 'Create one above to get started.',
    download: 'Download',
    delete: 'Delete',
    deleting: 'Deleting...',
    // Feedback page
    howWouldYouRate: 'How would you rate your experience?',
    commentOptional: 'Comment',
    commentPlaceholder: 'Tell us more about your experience...',
    optional: 'optional',
    submitFeedback: 'Submit Feedback',
    submitting: 'Submitting...',
    thankYou: 'Thank you!',
    feedbackSubmitted: 'Your feedback has been submitted.',
    feedbackClosed: 'Feedback Closed',
    qrInactive: 'This QR code is no longer active.',
    qrNotFound: 'QR Code Not Found',
    // Feedback list
    allFeedback: 'All Feedback',
    rating: 'Rating',
    comment: 'Comment',
    date: 'Date',
    qrName: 'QR Name',
    loadMore: 'Load More',
    // AI Summary
    aiSummary: 'AI Summary',
    dateFrom: 'From',
    dateTo: 'To',
    categoriesLabel: 'Categories',
    categoriesPlaceholder: 'e.g. cleanness, speed, service',
    generateSummary: 'Generate Summary',
    generating: 'Generating...',
    summaryTitle: 'Summary',
    noApiKey: 'AI summary is not configured. Add XAI_API_KEY to backend environment.',
    aiPresetToday: 'Today',
    aiPresetWeek: 'This Week',
    aiPresetMonth: 'This Month',
    aiPresetCustom: 'Custom',
    aiFocusAreas: 'Focus areas',
    aiAddFocusAreas: '+ Specify focus areas',
    aiFocusPlaceholder: 'e.g. service, speed, cleanliness',
    aiResponsesAnalysed: 'responses analysed',
    aiRegenerate: 'Regenerate',
    aiNoData: 'No feedback in this period to summarise.',
    // Super Admin
    totalCompanies: 'Total Companies',
    globalAvgRating: 'Global Average Rating',
    company: 'Company',
    slug: 'Slug',
    avgRating: 'Avg Rating',
    joined: 'Joined',
    // Admin
    adminSection: 'Admin',
    logoSettings: 'Company Logo',
    uploadLogo: 'Upload Logo',
    logoHint: 'Square image recommended. Will be cropped automatically.',
    logoSaved: 'Logo saved!',
    companySettings: 'Company Settings',
    companyNameLabel: 'Company Name',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    saved: 'Saved!',
    changePassword: 'Change Password',
    newPassword: 'New Password',
    updatePassword: 'Update Password',
    passwordUpdated: 'Password updated!',
    language: 'Language',
    languageSettings: 'Language',
    // Dashboard
    feedbackTrends: 'Feedback Trends',
    daily: 'Daily',
    weekly: 'Weekly',
    qrPerformance: 'QR Performance',
    recentHighlights: 'Recent Highlights',
    topRated: 'Top Rated',
    lowestRated: 'Lowest',
    aspects: 'Aspects',
    // Landing page
    landingBadge: 'Now accepting new partners',
    landingHeroTitle: 'Turn customer moments into business insights',
    landingHeroSubtitle: 'Place a QR code at any touchpoint. Customers rate in 10 seconds — no app, no login. You get live analytics, trends, and AI-generated summaries.',
    landingCTA: 'Request Partnership',
    landingSignIn: 'Sign In →',
    landingHowTitle: 'How it works',
    landingHowSubtitle: 'Three steps from setup to insight.',
    landingStep1Title: 'Generate a QR code',
    landingStep1Desc: 'Create QR codes for each location, table, or service point. Label them anything you like and manage them from your dashboard.',
    landingStep2Title: 'Customer scans & rates',
    landingStep2Desc: 'Customer scans with their phone camera. No app download, no account. They tap 1–10 and optionally leave a comment — done in 10 seconds.',
    landingStep3Title: 'See the data instantly',
    landingStep3Desc: 'Live dashboard with rating trends, per-location breakdowns, top & worst feedback highlights, and AI-generated category summaries.',
    landingWhyTitle: 'Why businesses choose RateBridge',
    landingWhySubtitle: 'Everything you need to understand what customers actually think.',
    landingF1Title: 'Zero friction',
    landingF1Desc: 'No app, no login, no personal info required. Customers complete feedback in under 10 seconds, so response rates stay high.',
    landingF2Title: 'Per-location insights',
    landingF2Desc: 'See which stations, rooms, or products perform best and worst — not just a single company-wide average.',
    landingF3Title: 'AI-powered summaries',
    landingF3Desc: 'Generate category-by-category breakdowns of your feedback using Groq AI for any date range you choose.',
    landingF4Title: 'Real-time trends',
    landingF4Desc: 'Daily and weekly charts update the moment a customer submits. Spot problems before they become patterns.',
    landingF5Title: 'Privacy first',
    landingF5Desc: 'Customers are fully anonymous. Only a hashed IP is stored for spam prevention — never linked to identity.',
    landingF6Title: 'Multi-language',
    landingF6Desc: 'Full English and German UI support out of the box, with more languages coming soon.',
    landingFormTitle: 'Request Partnership',
    landingFormSubtitle: 'Create your company account and start collecting real customer feedback today.',
    landingPasswordPlaceholder: 'Min. 8 characters',
    landingAlreadyPartner: 'Already a partner?',
    landingFooter: '© 2025 RateBridge. All rights reserved.',
    // Tasks
    tasks: 'Manage Tasks',
    newTask: 'New Task',
    taskTitle: 'Title',
    taskDescription: 'Description',
    taskDescriptionPlaceholder: 'What needs to be done? (optional)',
    taskTitlePlaceholder: 'e.g. Fix slow service at Table 5',
    taskStatus: 'Status',
    taskStatusBacklog: 'Backlog',
    taskStatusInProgress: 'In Progress',
    taskStatusResolved: 'Resolved',
    taskStatusRejected: 'Rejected',
    taskCreated: 'Created',
    taskUpdated: 'Updated',
    taskDelete: 'Delete',
    taskDeleteConfirm: 'Delete this task?',
    taskNoTasks: 'No tasks yet.',
    taskNoTasksHint: 'Create a task to start tracking issues from feedback.',
    taskFilterAll: 'All',
    taskIssuesOverview: 'Issues Overview',
    taskCancel: 'Cancel',
    taskSave: 'Save',
    taskEdit: 'Edit',
    taskAddTask: 'Add Task',
    taskResolutionRate: 'Resolution Rate',
    taskOpenIssues: 'open issues',
  },
  de: {
    // Nav
    dashboard: 'Dashboard',
    qrCodes: 'QR-Codes',
    feedback: 'Feedback',
    superAdmin: 'Super-Admin',
    logout: 'Abmelden',
    // Auth
    signIn: 'Anmelden',
    signingIn: 'Wird angemeldet...',
    signInSubtitle: 'Bei Ihrem Konto anmelden',
    noAccount: 'Kein Konto?',
    registerCompany: 'Unternehmen registrieren',
    alreadyHaveAccount: 'Bereits ein Konto?',
    createAccount: 'Konto erstellen',
    creatingAccount: 'Wird erstellt...',
    companyName: 'Unternehmensname',
    email: 'E-Mail',
    password: 'Passwort',
    // Dashboard
    overallPerformance: 'Gesamtleistung',
    totalFeedback: 'Gesamtfeedback',
    averageRating: 'Durchschnittsbewertung',
    outOf10: 'von 10',
    active: 'Aktiv',
    inactive: 'Inaktiv',
    activeQRCodes: 'Aktive QR-Codes',
    filter: 'Filter:',
    allQRCodes: 'Alle QR-Codes',
    showing: 'Angezeigt:',
    topFeedback: '🏆 Top-Feedback',
    needsAttention: '⚠️ Verbesserungsbedarf',
    noComment: 'Kein Kommentar',
    byQRCode: 'Nach QR-Code',
    responses: 'Antworten',
    avg: 'Ø',
    noFeedbackYet: 'Noch kein Feedback.',
    shareQRCodes: 'Teilen Sie Ihre QR-Codes, um Feedback zu sammeln.',
    dailyChart: 'Täglich — Letzte 30 Tage',
    weeklyChart: 'Wöchentlich — Letzte 4 Wochen',
    noDataPeriod: 'Noch kein Feedback in diesem Zeitraum.',
    ratingDistribution: 'Bewertungsverteilung',
    // QR Codes page
    generateNew: 'Neuen QR-Code generieren',
    labelPlaceholder: 'z. B. Haupteingang, Tisch 5...',
    create: 'Erstellen',
    creating: 'Wird erstellt...',
    noQRCodes: 'Noch keine QR-Codes.',
    createOneToStart: 'Erstellen Sie oben einen, um zu beginnen.',
    download: 'Herunterladen',
    delete: 'Löschen',
    deleting: 'Wird gelöscht...',
    // Feedback page
    howWouldYouRate: 'Wie bewerten Sie Ihre Erfahrung?',
    commentOptional: 'Kommentar',
    commentPlaceholder: 'Erzählen Sie uns mehr über Ihre Erfahrung...',
    optional: 'optional',
    submitFeedback: 'Feedback senden',
    submitting: 'Wird gesendet...',
    thankYou: 'Vielen Dank!',
    feedbackSubmitted: 'Ihr Feedback wurde übermittelt.',
    feedbackClosed: 'Feedback geschlossen',
    qrInactive: 'Dieser QR-Code ist nicht mehr aktiv.',
    qrNotFound: 'QR-Code nicht gefunden',
    // Feedback list
    allFeedback: 'Alle Feedbacks',
    rating: 'Bewertung',
    comment: 'Kommentar',
    date: 'Datum',
    qrName: 'QR-Name',
    loadMore: 'Mehr laden',
    // AI Summary
    aiSummary: 'KI-Zusammenfassung',
    dateFrom: 'Von',
    dateTo: 'Bis',
    categoriesLabel: 'Kategorien',
    categoriesPlaceholder: 'z. B. Sauberkeit, Geschwindigkeit, Service',
    generateSummary: 'Zusammenfassung erstellen',
    generating: 'Wird erstellt...',
    summaryTitle: 'Zusammenfassung',
    noApiKey: 'KI-Zusammenfassung nicht konfiguriert. XAI_API_KEY fehlt.',
    aiPresetToday: 'Heute',
    aiPresetWeek: 'Diese Woche',
    aiPresetMonth: 'Dieser Monat',
    aiPresetCustom: 'Benutzerdefiniert',
    aiFocusAreas: 'Schwerpunkte',
    aiAddFocusAreas: '+ Schwerpunkte festlegen',
    aiFocusPlaceholder: 'z. B. Service, Geschwindigkeit, Sauberkeit',
    aiResponsesAnalysed: 'Antworten analysiert',
    aiRegenerate: 'Neu erstellen',
    aiNoData: 'Kein Feedback in diesem Zeitraum zum Zusammenfassen.',
    // Super Admin
    totalCompanies: 'Unternehmen gesamt',
    globalAvgRating: 'Globale Ø-Bewertung',
    company: 'Unternehmen',
    slug: 'Slug',
    avgRating: 'Ø Bewertung',
    joined: 'Beigetreten',
    // Admin
    adminSection: 'Admin',
    logoSettings: 'Unternehmenslogo',
    uploadLogo: 'Logo hochladen',
    logoHint: 'Quadratisches Bild empfohlen. Wird automatisch zugeschnitten.',
    logoSaved: 'Logo gespeichert!',
    companySettings: 'Unternehmenseinstellungen',
    companyNameLabel: 'Unternehmensname',
    saveChanges: 'Änderungen speichern',
    saving: 'Wird gespeichert...',
    saved: 'Gespeichert!',
    changePassword: 'Passwort ändern',
    newPassword: 'Neues Passwort',
    updatePassword: 'Passwort aktualisieren',
    passwordUpdated: 'Passwort aktualisiert!',
    language: 'Sprache',
    languageSettings: 'Sprache',
    // Dashboard
    feedbackTrends: 'Feedback-Verlauf',
    daily: 'Täglich',
    weekly: 'Wöchentlich',
    qrPerformance: 'QR-Leistung',
    recentHighlights: 'Aktuelle Highlights',
    topRated: 'Beste',
    lowestRated: 'Schlechteste',
    aspects: 'Aspekte',
    // Landing page
    landingBadge: 'Jetzt neue Partner aufnehmen',
    landingHeroTitle: 'Kundenerlebnisse in Geschäftseinblicke verwandeln',
    landingHeroSubtitle: 'Platzieren Sie einen QR-Code an jedem Kontaktpunkt. Kunden bewerten in 10 Sekunden – keine App, kein Login. Sie erhalten Live-Analysen, Trends und KI-generierte Zusammenfassungen.',
    landingCTA: 'Partnerschaft anfragen',
    landingSignIn: 'Anmelden →',
    landingHowTitle: 'So funktioniert es',
    landingHowSubtitle: 'Drei Schritte vom Setup bis zum Einblick.',
    landingStep1Title: 'QR-Code generieren',
    landingStep1Desc: 'Erstellen Sie QR-Codes für jeden Standort, Tisch oder Servicepunkt. Benennen Sie sie nach Belieben und verwalten Sie sie über Ihr Dashboard.',
    landingStep2Title: 'Kunde scannt & bewertet',
    landingStep2Desc: 'Der Kunde scannt mit der Handykamera. Kein App-Download, kein Konto nötig. Er tippt 1–10 und hinterlässt optional einen Kommentar – fertig in 10 Sekunden.',
    landingStep3Title: 'Daten sofort einsehen',
    landingStep3Desc: 'Live-Dashboard mit Bewertungstrends, standortbezogenen Auswertungen, Top- & Worst-Highlights und KI-generierten Kategorienzusammenfassungen.',
    landingWhyTitle: 'Warum Unternehmen RateBridge wählen',
    landingWhySubtitle: 'Alles, was Sie brauchen, um zu verstehen, was Kunden wirklich denken.',
    landingF1Title: 'Kein Aufwand',
    landingF1Desc: 'Keine App, kein Login, keine persönlichen Daten erforderlich. Kunden geben Feedback in unter 10 Sekunden – für maximale Rücklaufquoten.',
    landingF2Title: 'Standortbezogene Einblicke',
    landingF2Desc: 'Sehen Sie, welche Stationen, Zimmer oder Produkte am besten und schlechtesten abschneiden – nicht nur ein Gesamtdurchschnitt.',
    landingF3Title: 'KI-gestützte Zusammenfassungen',
    landingF3Desc: 'Generieren Sie kategoriebezogene Auswertungen Ihres Feedbacks mit Groq AI für jeden gewünschten Zeitraum.',
    landingF4Title: 'Echtzeit-Trends',
    landingF4Desc: 'Tägliche und wöchentliche Diagramme aktualisieren sich sofort bei neuen Bewertungen. Erkennen Sie Probleme, bevor sie zum Muster werden.',
    landingF5Title: 'Datenschutz zuerst',
    landingF5Desc: 'Kunden sind vollständig anonym. Nur eine gehashte IP wird zur Spam-Prävention gespeichert – nie mit einer Identität verknüpft.',
    landingF6Title: 'Mehrsprachig',
    landingF6Desc: 'Vollständige Unterstützung für Englisch und Deutsch – weitere Sprachen folgen in Kürze.',
    landingFormTitle: 'Partnerschaft anfragen',
    landingFormSubtitle: 'Erstellen Sie Ihr Unternehmenskonto und beginnen Sie noch heute mit dem Sammeln von echtem Kundenfeedback.',
    landingPasswordPlaceholder: 'Mind. 8 Zeichen',
    landingAlreadyPartner: 'Bereits Partner?',
    landingFooter: '© 2025 RateBridge. Alle Rechte vorbehalten.',
    // Tasks
    tasks: 'Aufgaben verwalten',
    newTask: 'Neue Aufgabe',
    taskTitle: 'Titel',
    taskDescription: 'Beschreibung',
    taskDescriptionPlaceholder: 'Was muss getan werden? (optional)',
    taskTitlePlaceholder: 'z. B. Langsamen Service an Tisch 5 beheben',
    taskStatus: 'Status',
    taskStatusBacklog: 'Backlog',
    taskStatusInProgress: 'In Bearbeitung',
    taskStatusResolved: 'Erledigt',
    taskStatusRejected: 'Abgelehnt',
    taskCreated: 'Erstellt',
    taskUpdated: 'Aktualisiert',
    taskDelete: 'Löschen',
    taskDeleteConfirm: 'Diese Aufgabe löschen?',
    taskNoTasks: 'Noch keine Aufgaben.',
    taskNoTasksHint: 'Erstellen Sie eine Aufgabe, um Probleme aus Feedback zu verfolgen.',
    taskFilterAll: 'Alle',
    taskIssuesOverview: 'Aufgabenübersicht',
    taskCancel: 'Abbrechen',
    taskSave: 'Speichern',
    taskEdit: 'Bearbeiten',
    taskAddTask: 'Aufgabe hinzufügen',
    taskResolutionRate: 'Erledigungsrate',
    taskOpenIssues: 'offene Aufgaben',
  },
} as const

type TranslationKey = keyof typeof translations.en

interface LanguageContextValue {
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: TranslationKey) => string
}

const LanguageContext = createContext<LanguageContextValue | null>(null)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    return (localStorage.getItem('lang') as Lang) || 'en'
  })

  const switchLang = (l: Lang) => {
    setLang(l)
    localStorage.setItem('lang', l)
  }

  const t = (key: TranslationKey): string => translations[lang][key] ?? key

  return (
    <LanguageContext.Provider value={{ lang, setLang: switchLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}
