import React, { createContext, useContext, useState } from 'react'

type Lang = 'en' | 'de'

const translations = {
  en: {
    // Nav
    dashboard: 'Dashboard',
    qrCodes: 'QR Codes',
    feedback: 'Feedback',
    superAdmin: 'Super Admin',
    logout: 'Logout',
    // Auth
    signIn: 'Sign In',
    signingIn: 'Signing in...',
    signInSubtitle: 'Sign in to your account',
    noAccount: 'No account?',
    registerCompany: 'Register your company',
    alreadyHaveAccount: 'Already have an account?',
    createAccount: 'Create Account',
    creatingAccount: 'Creating account...',
    companyName: 'Company Name',
    email: 'Email',
    password: 'Password',
    // Dashboard
    overallPerformance: 'Overall performance',
    totalFeedback: 'Total Feedback',
    averageRating: 'Average Rating',
    outOf10: 'out of 10',
    active: 'Active',
    inactive: 'Inactive',
    activeQRCodes: 'Active QR Codes',
    filter: 'Filter:',
    allQRCodes: 'All QR Codes',
    showing: 'Showing:',
    topFeedback: '🏆 Top Feedback',
    needsAttention: '⚠️ Needs Attention',
    noComment: 'No comment',
    byQRCode: 'By QR Code',
    responses: 'responses',
    avg: 'avg',
    noFeedbackYet: 'No feedback yet.',
    shareQRCodes: 'Share your QR codes to start collecting feedback.',
    dailyChart: 'Daily — Last 30 Days',
    weeklyChart: 'Weekly — Last 4 Weeks',
    noDataPeriod: 'No feedback in this period yet.',
    ratingDistribution: 'Rating Distribution',
    // QR Codes page
    generateNew: 'Generate New QR Code',
    labelPlaceholder: 'e.g. Main Entrance, Table 5...',
    create: 'Create',
    creating: 'Creating...',
    noQRCodes: 'No QR codes yet.',
    createOneToStart: 'Create one above to get started.',
    download: 'Download',
    delete: 'Delete',
    deleting: 'Deleting...',
    // Feedback page
    howWouldYouRate: 'How would you rate your experience?',
    commentOptional: 'Comment',
    commentPlaceholder: 'Tell us more about your experience...',
    optional: 'optional',
    submitFeedback: 'Submit Feedback',
    submitting: 'Submitting...',
    thankYou: 'Thank you!',
    feedbackSubmitted: 'Your feedback has been submitted.',
    feedbackClosed: 'Feedback Closed',
    qrInactive: 'This QR code is no longer active.',
    qrNotFound: 'QR Code Not Found',
    // Feedback list
    allFeedback: 'All Feedback',
    rating: 'Rating',
    comment: 'Comment',
    date: 'Date',
    qrName: 'QR Name',
    loadMore: 'Load More',
    // AI Summary
    aiSummary: 'AI Summary',
    dateFrom: 'From',
    dateTo: 'To',
    categoriesLabel: 'Categories',
    categoriesPlaceholder: 'e.g. cleanness, speed, service',
    generateSummary: 'Generate Summary',
    generating: 'Generating...',
    summaryTitle: 'Summary',
    noApiKey: 'AI summary is not configured. Add XAI_API_KEY to backend environment.',
    aiPresetToday: 'Today',
    aiPresetWeek: 'This Week',
    aiPresetMonth: 'This Month',
    aiPresetCustom: 'Custom',
    aiFocusAreas: 'Focus areas',
    aiAddFocusAreas: '+ Specify focus areas',
    aiFocusPlaceholder: 'e.g. service, speed, cleanliness',
    aiResponsesAnalysed: 'responses analysed',
    aiRegenerate: 'Regenerate',
    aiNoData: 'No feedback in this period to summarise.',
    // Super Admin
    totalCompanies: 'Total Companies',
    globalAvgRating: 'Global Average Rating',
    company: 'Company',
    slug: 'Slug',
    avgRating: 'Avg Rating',
    joined: 'Joined',
    // Admin
    adminSection: 'Admin',
    logoSettings: 'Company Logo',
    uploadLogo: 'Upload Logo',
    logoHint: 'Square image recommended. Will be cropped automatically.',
    logoSaved: 'Logo saved!',
    companySettings: 'Company Settings',
    companyNameLabel: 'Company Name',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    saved: 'Saved!',
    changePassword: 'Change Password',
    newPassword: 'New Password',
    updatePassword: 'Update Password',
    passwordUpdated: 'Password updated!',
    language: 'Language',
    languageSettings: 'Language',
    // Dashboard
    feedbackTrends: 'Feedback Trends',
    daily: 'Daily',
    weekly: 'Weekly',
    qrPerformance: 'QR Performance',
    recentHighlights: 'Recent Highlights',
    topRated: 'Top Rated',
    lowestRated: 'Lowest',
    aspects: 'Aspects',
    // Landing page
    landingBadge: 'Now accepting new partners',
    landingHeroTitle: 'Close the loop between what customers feel and what your team fixes',
    landingHeroSubtitle: 'RateBridge is the shortest path from a customer\'s moment of experience to the people who can act on it — through instant QR ratings, AI-powered analysis, and built-in task tracking.',
    landingCTA: 'Request Partnership',
    landingSignIn: 'Sign In →',
    landingHowTitle: 'One loop. Four steps.',
    landingHowSubtitle: 'Most feedback tools stop at data collection. RateBridge takes you all the way to resolution.',
    landingStep1Title: 'Customer rates in 10 seconds',
    landingStep1Desc: 'They scan a QR code at any touchpoint — table, counter, room, receipt. No app, no login, fully anonymous.',
    landingStep2Title: 'You see it instantly',
    landingStep2Desc: 'Every rating lands in your live dashboard the moment it\'s submitted. Per-location, per-QR code, real-time.',
    landingStep3Title: 'AI surfaces the patterns',
    landingStep3Desc: 'Generate structured summaries for today, this week, or any period. Spot what matters before it becomes a bigger problem.',
    landingStep4Title: 'Your team acts and closes the loop',
    landingStep4Desc: 'Create tasks from insights. Track them from Backlog → In Progress → Resolved. Measure your resolution rate.',
    landingWhyTitle: 'Everything in one loop',
    landingWhySubtitle: 'Three stages, one platform — from the moment of experience to the moment of resolution.',
    landingP1Name: 'Capture',
    landingP1Sub: 'Zero friction for customers',
    landingP1B1: 'QR codes for every location, table, or service point',
    landingP1B2: 'Customers rate in 10 seconds — no app, no account',
    landingP1B3: 'Fully anonymous — only a hashed IP for spam prevention',
    landingP1B4: 'Unlimited QR codes, custom labels, editable anytime',
    landingP2Name: 'Understand',
    landingP2Sub: 'Intelligence, not just data',
    landingP2B1: 'Live dashboard with real-time ratings and trends',
    landingP2B2: 'AI summaries — Today, This Week, This Month — one click',
    landingP2B3: 'Per-location performance breakdown and leaderboard',
    landingP2B4: 'Top and worst feedback highlights at a glance',
    landingP3Name: 'Act',
    landingP3Sub: 'Close the loop — the part most tools skip',
    landingP3B1: 'Create tasks directly from feedback patterns',
    landingP3B2: 'Track each issue: Backlog → In Progress → Resolved',
    landingP3B3: 'Resolution rate analytics to measure team performance',
    landingP3B4: 'The full loop: customer experience → business action',
    landingProblemTitle: 'The gap most businesses never close',
    landingProblemText: 'Feedback collected on paper, email surveys, or review platforms rarely reaches the people who can act on it — and even when it does, there\'s no way to track whether anything was actually fixed. RateBridge bridges that gap.',
    landingFormTitle: 'Request Partnership',
    landingFormSubtitle: 'Create your company account and start closing the loop today.',
    landingPasswordPlaceholder: 'Min. 8 characters',
    landingAlreadyPartner: 'Already a partner?',
    landingFooter: '© 2025 RateBridge. All rights reserved.',
    landingPreviewTitle: 'See the product in action',
    landingPreviewSub: 'A live look at what your team uses every day — from the moment a rating comes in to the moment an issue is resolved.',
    // Tasks
    tasks: 'Manage Tasks',
    newTask: 'New Task',
    taskTitle: 'Title',
    taskDescription: 'Description',
    taskDescriptionPlaceholder: 'What needs to be done? (optional)',
    taskTitlePlaceholder: 'e.g. Fix slow service at Table 5',
    taskStatus: 'Status',
    taskStatusBacklog: 'Backlog',
    taskStatusInProgress: 'In Progress',
    taskStatusResolved: 'Resolved',
    taskStatusRejected: 'Rejected',
    taskCreated: 'Created',
    taskUpdated: 'Updated',
    taskDelete: 'Delete',
    taskDeleteConfirm: 'Delete this task?',
    taskNoTasks: 'No tasks yet.',
    taskNoTasksHint: 'Create a task to start tracking issues from feedback.',
    taskFilterAll: 'All',
    taskIssuesOverview: 'Issues Overview',
    taskCancel: 'Cancel',
    taskSave: 'Save',
    taskEdit: 'Edit',
    taskAddTask: 'Add Task',
    taskResolutionRate: 'Resolution Rate',
    taskOpenIssues: 'open issues',
  },
  de: {
    // Nav
    dashboard: 'Dashboard',
    qrCodes: 'QR-Codes',
    feedback: 'Feedback',
    superAdmin: 'Super-Admin',
    logout: 'Abmelden',
    // Auth
    signIn: 'Anmelden',
    signingIn: 'Wird angemeldet...',
    signInSubtitle: 'Bei Ihrem Konto anmelden',
    noAccount: 'Kein Konto?',
    registerCompany: 'Unternehmen registrieren',
    alreadyHaveAccount: 'Bereits ein Konto?',
    createAccount: 'Konto erstellen',
    creatingAccount: 'Wird erstellt...',
    companyName: 'Unternehmensname',
    email: 'E-Mail',
    password: 'Passwort',
    // Dashboard
    overallPerformance: 'Gesamtleistung',
    totalFeedback: 'Gesamtfeedback',
    averageRating: 'Durchschnittsbewertung',
    outOf10: 'von 10',
    active: 'Aktiv',
    inactive: 'Inaktiv',
    activeQRCodes: 'Aktive QR-Codes',
    filter: 'Filter:',
    allQRCodes: 'Alle QR-Codes',
    showing: 'Angezeigt:',
    topFeedback: '🏆 Top-Feedback',
    needsAttention: '⚠️ Verbesserungsbedarf',
    noComment: 'Kein Kommentar',
    byQRCode: 'Nach QR-Code',
    responses: 'Antworten',
    avg: 'Ø',
    noFeedbackYet: 'Noch kein Feedback.',
    shareQRCodes: 'Teilen Sie Ihre QR-Codes, um Feedback zu sammeln.',
    dailyChart: 'Täglich — Letzte 30 Tage',
    weeklyChart: 'Wöchentlich — Letzte 4 Wochen',
    noDataPeriod: 'Noch kein Feedback in diesem Zeitraum.',
    ratingDistribution: 'Bewertungsverteilung',
    // QR Codes page
    generateNew: 'Neuen QR-Code generieren',
    labelPlaceholder: 'z. B. Haupteingang, Tisch 5...',
    create: 'Erstellen',
    creating: 'Wird erstellt...',
    noQRCodes: 'Noch keine QR-Codes.',
    createOneToStart: 'Erstellen Sie oben einen, um zu beginnen.',
    download: 'Herunterladen',
    delete: 'Löschen',
    deleting: 'Wird gelöscht...',
    // Feedback page
    howWouldYouRate: 'Wie bewerten Sie Ihre Erfahrung?',
    commentOptional: 'Kommentar',
    commentPlaceholder: 'Erzählen Sie uns mehr über Ihre Erfahrung...',
    optional: 'optional',
    submitFeedback: 'Feedback senden',
    submitting: 'Wird gesendet...',
    thankYou: 'Vielen Dank!',
    feedbackSubmitted: 'Ihr Feedback wurde übermittelt.',
    feedbackClosed: 'Feedback geschlossen',
    qrInactive: 'Dieser QR-Code ist nicht mehr aktiv.',
    qrNotFound: 'QR-Code nicht gefunden',
    // Feedback list
    allFeedback: 'Alle Feedbacks',
    rating: 'Bewertung',
    comment: 'Kommentar',
    date: 'Datum',
    qrName: 'QR-Name',
    loadMore: 'Mehr laden',
    // AI Summary
    aiSummary: 'KI-Zusammenfassung',
    dateFrom: 'Von',
    dateTo: 'Bis',
    categoriesLabel: 'Kategorien',
    categoriesPlaceholder: 'z. B. Sauberkeit, Geschwindigkeit, Service',
    generateSummary: 'Zusammenfassung erstellen',
    generating: 'Wird erstellt...',
    summaryTitle: 'Zusammenfassung',
    noApiKey: 'KI-Zusammenfassung nicht konfiguriert. XAI_API_KEY fehlt.',
    aiPresetToday: 'Heute',
    aiPresetWeek: 'Diese Woche',
    aiPresetMonth: 'Dieser Monat',
    aiPresetCustom: 'Benutzerdefiniert',
    aiFocusAreas: 'Schwerpunkte',
    aiAddFocusAreas: '+ Schwerpunkte festlegen',
    aiFocusPlaceholder: 'z. B. Service, Geschwindigkeit, Sauberkeit',
    aiResponsesAnalysed: 'Antworten analysiert',
    aiRegenerate: 'Neu erstellen',
    aiNoData: 'Kein Feedback in diesem Zeitraum zum Zusammenfassen.',
    // Super Admin
    totalCompanies: 'Unternehmen gesamt',
    globalAvgRating: 'Globale Ø-Bewertung',
    company: 'Unternehmen',
    slug: 'Slug',
    avgRating: 'Ø Bewertung',
    joined: 'Beigetreten',
    // Admin
    adminSection: 'Admin',
    logoSettings: 'Unternehmenslogo',
    uploadLogo: 'Logo hochladen',
    logoHint: 'Quadratisches Bild empfohlen. Wird automatisch zugeschnitten.',
    logoSaved: 'Logo gespeichert!',
    companySettings: 'Unternehmenseinstellungen',
    companyNameLabel: 'Unternehmensname',
    saveChanges: 'Änderungen speichern',
    saving: 'Wird gespeichert...',
    saved: 'Gespeichert!',
    changePassword: 'Passwort ändern',
    newPassword: 'Neues Passwort',
    updatePassword: 'Passwort aktualisieren',
    passwordUpdated: 'Passwort aktualisiert!',
    language: 'Sprache',
    languageSettings: 'Sprache',
    // Dashboard
    feedbackTrends: 'Feedback-Verlauf',
    daily: 'Täglich',
    weekly: 'Wöchentlich',
    qrPerformance: 'QR-Leistung',
    recentHighlights: 'Aktuelle Highlights',
    topRated: 'Beste',
    lowestRated: 'Schlechteste',
    aspects: 'Aspekte',
    // Landing page
    landingBadge: 'Jetzt neue Partner aufnehmen',
    landingHeroTitle: 'Schließen Sie die Lücke zwischen dem, was Kunden fühlen, und dem, was Ihr Team behebt',
    landingHeroSubtitle: 'RateBridge ist der kürzeste Weg vom Kundenerlebnis zu den Menschen, die handeln können — durch sofortige QR-Bewertungen, KI-gestützte Analyse und integriertes Aufgabenmanagement.',
    landingCTA: 'Partnerschaft anfragen',
    landingSignIn: 'Anmelden →',
    landingHowTitle: 'Ein Kreislauf. Vier Schritte.',
    landingHowSubtitle: 'Die meisten Feedback-Tools enden bei der Datenerfassung. RateBridge bringt Sie bis zur Lösung.',
    landingStep1Title: 'Kunde bewertet in 10 Sekunden',
    landingStep1Desc: 'Er scannt einen QR-Code an jedem Kontaktpunkt — Tisch, Theke, Zimmer, Kassenbon. Keine App, kein Login, vollständig anonym.',
    landingStep2Title: 'Sie sehen es sofort',
    landingStep2Desc: 'Jede Bewertung erscheint im Moment der Abgabe in Ihrem Live-Dashboard. Nach Standort, nach QR-Code, in Echtzeit.',
    landingStep3Title: 'KI erkennt die Muster',
    landingStep3Desc: 'Erstellen Sie strukturierte Zusammenfassungen für heute, diese Woche oder einen beliebigen Zeitraum. Erkennen Sie, was wichtig ist, bevor es ein größeres Problem wird.',
    landingStep4Title: 'Ihr Team handelt und schließt den Kreislauf',
    landingStep4Desc: 'Erstellen Sie Aufgaben aus Erkenntnissen. Verfolgen Sie sie von Backlog → In Bearbeitung → Erledigt. Messen Sie Ihre Lösungsrate.',
    landingWhyTitle: 'Alles in einem Kreislauf',
    landingWhySubtitle: 'Drei Phasen, eine Plattform — vom Erlebnismoment bis zur Lösung.',
    landingP1Name: 'Erfassen',
    landingP1Sub: 'Kein Aufwand für Kunden',
    landingP1B1: 'QR-Codes für jeden Standort, Tisch oder Servicepunkt',
    landingP1B2: 'Kunden bewerten in 10 Sekunden — keine App, kein Konto',
    landingP1B3: 'Vollständig anonym — nur eine gehashte IP gegen Spam',
    landingP1B4: 'Unbegrenzte QR-Codes, benutzerdefinierte Labels, jederzeit bearbeitbar',
    landingP2Name: 'Verstehen',
    landingP2Sub: 'Intelligenz, nicht nur Daten',
    landingP2B1: 'Live-Dashboard mit Echtzeit-Bewertungen und Trends',
    landingP2B2: 'KI-Zusammenfassungen — Heute, Diese Woche, Dieser Monat — ein Klick',
    landingP2B3: 'Standortbezogene Leistungsauswertung und Rangliste',
    landingP2B4: 'Top- und schlechteste Feedback-Highlights auf einen Blick',
    landingP3Name: 'Handeln',
    landingP3Sub: 'Den Kreislauf schließen — was die meisten Tools überspringen',
    landingP3B1: 'Aufgaben direkt aus Feedback-Mustern erstellen',
    landingP3B2: 'Jedes Problem verfolgen: Backlog → In Bearbeitung → Erledigt',
    landingP3B3: 'Lösungsraten-Analyse zur Messung der Teamleistung',
    landingP3B4: 'Der vollständige Kreislauf: Kundenerlebnis → Geschäftliche Maßnahme',
    landingProblemTitle: 'Die Lücke, die die meisten Unternehmen nie schließen',
    landingProblemText: 'Feedback auf Papier, per E-Mail oder auf Bewertungsplattformen erreicht selten die Menschen, die handeln können — und selbst dann gibt es keine Möglichkeit zu verfolgen, ob tatsächlich etwas behoben wurde. RateBridge überbrückt diese Lücke.',
    landingFormTitle: 'Partnerschaft anfragen',
    landingFormSubtitle: 'Erstellen Sie Ihr Unternehmenskonto und schließen Sie den Kreislauf noch heute.',
    landingPasswordPlaceholder: 'Mind. 8 Zeichen',
    landingAlreadyPartner: 'Bereits Partner?',
    landingFooter: '© 2025 RateBridge. Alle Rechte vorbehalten.',
    landingPreviewTitle: 'Das Produkt in Aktion',
    landingPreviewSub: 'Ein Live-Blick auf das, was Ihr Team täglich nutzt — vom Eingang einer Bewertung bis zur Lösung eines Problems.',
    // Tasks
    tasks: 'Aufgaben verwalten',
    newTask: 'Neue Aufgabe',
    taskTitle: 'Titel',
    taskDescription: 'Beschreibung',
    taskDescriptionPlaceholder: 'Was muss getan werden? (optional)',
    taskTitlePlaceholder: 'z. B. Langsamen Service an Tisch 5 beheben',
    taskStatus: 'Status',
    taskStatusBacklog: 'Backlog',
    taskStatusInProgress: 'In Bearbeitung',
    taskStatusResolved: 'Erledigt',
    taskStatusRejected: 'Abgelehnt',
    taskCreated: 'Erstellt',
    taskUpdated: 'Aktualisiert',
    taskDelete: 'Löschen',
    taskDeleteConfirm: 'Diese Aufgabe löschen?',
    taskNoTasks: 'Noch keine Aufgaben.',
    taskNoTasksHint: 'Erstellen Sie eine Aufgabe, um Probleme aus Feedback zu verfolgen.',
    taskFilterAll: 'Alle',
    taskIssuesOverview: 'Aufgabenübersicht',
    taskCancel: 'Abbrechen',
    taskSave: 'Speichern',
    taskEdit: 'Bearbeiten',
    taskAddTask: 'Aufgabe hinzufügen',
    taskResolutionRate: 'Erledigungsrate',
    taskOpenIssues: 'offene Aufgaben',
  },
} as const

type TranslationKey = keyof typeof translations.en

interface LanguageContextValue {
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: TranslationKey) => string
}

const LanguageContext = createContext<LanguageContextValue | null>(null)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    return (localStorage.getItem('lang') as Lang) || 'en'
  })

  const switchLang = (l: Lang) => {
    setLang(l)
    localStorage.setItem('lang', l)
  }

  const t = (key: TranslationKey): string => translations[lang][key] ?? key

  return (
    <LanguageContext.Provider value={{ lang, setLang: switchLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}
